### ISSUE TITLE
avoid projecting segments below the zero

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#10]
**Course: PES**

**Project group id: PES-TEACHER**

**Describe the improvement**
In the historical view, when showing the reference segment interpolated from the values, the lowest value shouldn't be lower than 0 (see screenshot below with the problem)

**Where Affects**
Historical view

**Expected behavior**
Take 0 as lower value when necessary to avoid segments projecting below 0

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10616582/165262130-f020f634-45bb-423d-8364-da1763bca77b.png)

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by jdconejos** [comment]
The trendline now stops when the value is below zero, however it can still surpass the upper limit of the graph. This is because of a limitation of the plugin we use to draw the line.
