### ISSUE TITLE
Add help information to the factor and metrics

### ISSUE THREAD

**Issue by AleixLinares** [Learning-Dashboard/Bug-Reporting#11]
**Course: ASW/PES**

**Project group id: developer**

**Describe the improvement**
A text that shows a description of the metrics inside each factor.

**Where Affects**
Views where the improvement should apply (take view names from URL):
1. QualityFactors/HistoricChart(maybe)
2. Metrics/CurrentTable

**Expected behavior**
Next to each factor title there is an image with a "?" or "i" symbol that when hovering over it shows the description of the metrics inside the factor.

**Screenshots**
Not yet

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by AleixLinares** [comment]
Before closing this issue I will implement the same funcionality using a different method that allows for a more editable displayded texts.

**Comment by carlesf** [comment]
OK
