### ISSUE TITLE
Refactor of the quality factors(Creation of different categories)

### ISSUE THREAD

**Issue by AleixLinares** [Learning-Dashboard/Bug-Reporting#12]
**Course: ASW/PES**

**Project group id: developer**

**Describe the improvement**
Having different categories for each factor

**Where Affects**
Views where the improvement should apply (take view names from URL):
1. QualityFactors/HistoricChart

**Expected behavior**
Add a categories creator for quality factors with different names.  

**Screenshots**
N/A

**Technical context (if it is relevant):**
N/A

**Additional context**
This refactor is the same to the one done with the metrics categories

**Comment by alejandravv** [comment]
Closed due to deploy on the server.
