### ISSUE TITLE
Error 500: JWT String argument cannot be null or empty.

### ISSUE THREAD

**Issue by alejandravv** [Learning-Dashboard/Bug-Reporting#13]
**Course: ASW/PES**

**Project group id: Developer**

**Describe the bug**
Sometimes after inactivity, when some action is done on dashboard without reload the page previously, it's produce error 500 "JWT String argument cannot be null or empty" (see screenshots). After that, it is impossible to go to a login page.

**To Reproduce**
1. Stay on any dashboard page
2. Wait for inactivity timeout (15 minutes)
3. Make any action without reloading the page

**Expected behavior**
Understand the origin of error and permit to go to login page correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/48628943/166222084-9b01e1bf-a86a-4295-98ce-9c6516e864a3.png)

**Technical context (if it is relevant):**
N/A

**Additional context**
If open dashboard on new tad or new secret tab it will work, maybe it's problem with cookies.

**Comment by carlesf** [comment]
Sembla que funciona
