### ISSUE TITLE
New GitHub metric: % of 'anonymous' commits

### ISSUE THREAD

**Issue by carlesf** [Learning-Dashboard/Bug-Reporting#14]
**Course: ASW/PES**

**Project group id: N/A**

**Describe the improvement**
Some students forget to configure their git credentials in their local environments. Consequently, the commits that they push to GitHub from these local branches don't match with any known contributor. A simple metric showing the % of commits whose author is unknown would allow the detection of this problem.

**Where Affects**
Definition of a new metric and its corresponding visualizations. Perhaps it can be taken into account to define some factor that assesses the quality of commits, together with the metric that checks if the commit messages point to a Taiga task.

**Comment by alejandravv** [comment]
Due to we do not want to alter existing factor Commits Tasks Relation, we add this metric as separated factor Commits Management, which is included in Repository Contribution indicator.
