### ISSUE TITLE
Total number of tasks

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#17]
**Course: PES**

**Project group id: PES-TEACHER**

**Describe the improvement**
In order to allow a better contextualization of task-related metrics, having available the total number of tasks would help. Especially in the historical charts.

**Where Affects**
Mostly metrics, and then as needed in other views

**Expected behavior**
A new metric to be added in the task-related family

**Screenshots**
N/A

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by carlesf** [comment]
[XF] potser podríem introduir un altre concepte, e.g. Context Variable (o com sigui), pq en realitat el seu valor no s'usarà per mesurar la qualitat sinó que ajudarà a interpretar la resta de mètriques 
(Source: [2022-05-04 Reunió "Vista Professor"](https://drive.google.com/open?id=1QxmZnYp2EzR8_dl2NNUbaU2pi6gc-vMM6FWD4drFqec) )

**Comment by carlesf** [comment]
[XF] en tot cas, si cal normalitzar entre 0 i 1, sempre es pot agafar com a numerador a cada dia el nombre de tasques d'aquell dia, i com a denominador el nombre màxim de tasques de la iteració (assumeixo que ens interessa la iteració only)
(Source: [2022-05-04 Reunió "Vista Professor"](https://drive.google.com/open?id=1QxmZnYp2EzR8_dl2NNUbaU2pi6gc-vMM6FWD4drFqec) )

**Comment by jdconejos** [comment]
This context information has been added in the metric historic view, when the user hovers the mouse on a point in the graph, as shown in the image:

![image](https://user-images.githubusercontent.com/79250937/179731341-c9d3674d-6434-41e8-9edd-a42857bafcb7.png)
