### ISSUE TITLE
Create a template for Taiga

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#19]
**Course: PES**

**Project group id: PES-TEACHER**

**Describe the improvement**
(Not related to the dashboard, but to Taiga.) Delegating onto the students the creation of additional fields to be used by the dashboard increases the likelihood of errors in the connectors, and represents an extra workload for students

**Where Affects**
Affects data connectors

**Expected behavior**
Students see in Taiga a template that they can use in order to define their user stories and tasks

**Screenshots**
N/A

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by AleixLinares** [comment]
In the link below we can find a file that explains how to create and use templates for Taiga with some notes. We can can also find and example of a template with some elements already configured.

https://drive.google.com/drive/u/1/folders/1bUdX3b4mJMH20td_faSZOXodt4oTebhH
