### ISSUE TITLE
Metrics' names not fully displayed

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#2]
**Course: PES**

**Project group id: PES-teacher**

**Describe the improvement**
Avoid "..." in metrics' name, since it may affect readability (sometimes, it is not evident to guess the full name)

**Where Affects**
All cockpit-like view of metrics

**Expected behavior**
Visualize the entire or at least large-enough part of the metrics' name. Either by shortening the displayed name, or separating the metrics among them (probably most problematic)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10616582/157860119-fb868534-4509-4021-a963-2708578f8f9b.png)
This is an extreme example

**Technical context (if it is relevant):** 
Non-relevant

**Additional context**
None

**Comment by jdconejos** [comment]
Hello Xavier,
The three dots you mentioned have been removed and now the full metric's name is shown
