### ISSUE TITLE
Metrics Historical view don't group by factor well

### ISSUE THREAD

**Issue by alejandravv** [Learning-Dashboard/Bug-Reporting#25]
**Course: ASW/PES**

**Project group id: Developer**

**Describe the bug**
Depending on the interval selected for the historical view of the metrics, there are factors that have no data for this period, but are displayed and as a consequence other graphs are messed up.

**To Reproduce**
1. Go to /Metrics/HistoricChart view (e.g. hn11b)
2. Click on Interval (e.g. Delivirable 1)
3. Scroll down to 'Commits Management' factor
4. See error, this factor has data from another metric.

**Expected behavior**
The behavior must be similar to Factos or Detailed Factors Historical view, when the factor don't have data for the selected period/interval, it should not be shown.

**Screenshots**
Messed up data on Metrics Historical view:
![image](https://user-images.githubusercontent.com/48628943/177270128-79dc5b43-89e2-4ae2-8454-15d049d4e7ca.png)

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by AleixLinares** [comment]
The factors that have no data for a certain period of time are removed from the view and are not shown
