### ISSUE TITLE
Reconsider visible views over metrics

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#3]
**Course: PES**

**Project group id: PES-teacher**

**Describe the improvement**
Reconsider the different possibilities of visualizing metrics

**Where Affects**
Metrics' views

**Expected behavior**
Currently, metrics can be visualized either without any arrangement or grouped by factors (in case of cockpits). My point is that without any arrangement, visualization is mostly useless (it is very difficult to see anything). Instead, I suggest to brainstorm more advanced capabilities. For instance, one that I see fit is to add a filter to show only team-level metrics (not individual metrics). Another view that needs some study is teacher-oriented: provide a view that facilitates the overall comparison of students (see second screenshort, a kind of mock-up). 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10616582/157861767-5c07bb27-0871-4c39-aff1-276df8356eda.png)

This shows that the plain all-metrics view is very difficult to comprehend.

![imagen](https://user-images.githubusercontent.com/10616582/157862763-9e0088cb-01f7-45be-bf40-ca163a70b37e.png)

This shows an envisaged way to show metrics arranged by student (metrics also grouped by factor, which I think should be the default)

**Technical context (if it is relevant):**
N/A

**Additional context**
None

**Comment by jdconejos** [comment]
Hello Xavier,
At the moment, the default view has been switched to the "group by factor" view. 
Implementing the metric gauges as you suggested would require significant changes in both the database and web page, that's why we considered changing the default view as a "quick fix". Nevertheless, I believe this improvement to be a good idea as a long-term goal.
