### ISSUE TITLE
Error Kafka Github Connector

### ISSUE THREAD

**Issue by alili707** [Learning-Dashboard/Bug-Reporting#35]
**Course: ASW/PES**

**Project group id: all**

**Describe the bug**
When turning on (only turning on, not when creating it) the docker qrconnect_github container of any team, the task fails. It only works if the container is removed and recomposed. 

**To Reproduce**
1. Go to Learning Dashboard folder.
2. Make sure Kafka and Zookeeper are turned on and have been for at least 2 minutes.
3. Make sure the GitHub container of the team exists and is turned off. If not, create it and turn it off.
4. Turn on the container.
5. Check the logs.

**Expected behavior**
It is expected to establish a successful connection and to be able to check on the logs how the polling is being made. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96695359/193421587-49abd63f-ee03-4dc8-abe6-38f73fdd1878.png)

**Technical context (if it is relevant):**
Not relevant

**Comment by carlesf** [comment]
Solucionat!
