### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#4]
**Course: PES**

**Project group id: PES-teacher**

**Describe the improvement**
Implement session timeout

**Where Affects**
The full session

**Expected behavior**
The session automatically closes after let's say 15 minutes of inactivity

**Screenshots**
N/A

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by AleixLinares** [comment]
Hello Xavier,

Now the session ends after 15 minutes of inactivity. If you try to do something after 15 minutes of inactivity it redirects you to the login page. It has been done using the session manager already implemented but reducing the lifetime of the cookies and refreshing them when needed.
