### ISSUE TITLE
A un estudiant no es mostren correctament les mètriques

### ISSUE THREAD

**Issue by carlesf** [Learning-Dashboard/Bug-Reporting#40]
En el projecte j12c, a l'apartat mètriques, agrupat per estudiants, es veu que a l'Andrei-Constantin Popa li falten dues mètriques del GitHub: commits i modified Lines (no és que estiguin a 0, és que no hi són), però agrupat per factors sí que apareixen. 
A més, mirant al Quality Model, la cosa és més rara pq veig el contrari del que m'esperaria per aquest error: a "Fullimelment of Tasks" i "Tasks Contributions" tenen associats 6 estudiants, mentre que a "commits contribution" i "modified lines" tenen associats 7 estudiants. En qualsevol cas, s'ha de revisar.

**Comment by lauracazorla** [comment]
El caràcter "-" del seu username de Github donava problemes quan s'utilitzava als noms dels fitxers dels connectors. L'hem substituït per el caràcter "_" i ja funciona correctament.
