### ISSUE TITLE
S'han de revisar els labels de tots els factors

### ISSUE THREAD

**Issue by carlesf** [Learning-Dashboard/Bug-Reporting#41]
S'haurien d'arreglar els labels del factors que qualitat.

### Commits management
- En el grup s11a, està a taronja però el label posa 'Well'
- En el grup s11b, està  a verd però el label posa 'Down'
- En el grup s11c, també està en verd però el label posa 'Bad'.

 ###  Commits tasks Relation
- Al grup s11c en vermell posa 'Low', als altres grups posa 'Bad', s'hauria d'uniformitzar a "Low".

 ### Deviation metrics
- Al grup j12b en verd posa 'Down', al j12c i s11a en verd posa 'Low', al grup s11b i s11c en verd posa 'Well'.

 ### Fulfillment of tasks
- Al grup s11a, en taronja posa 'Up' en comptes de 'Neutral'

 ### Tasks Contributions
- Al grup s11a, s11b en verd posa 'Down'
- Al grup s11c i j12b en taronja posa 'Low'. És correcte?

 ### Task effort Information
- El grup j12b, en vermell posa 'Low'; al grup s11c, en taronja posa 'Low'; al grup j12c en vermell posa 'Bad'.

 ### Unassigned tasks:
- Al grup j12b i s11a, en taronja posa 'Up'.
- Al grup j12c en verd posa 'Bad'.

 ### User Stories Defintion Quality:
- Al grup s11a, en vermell posa 'Up'.

**Comment by teyteymey** [comment]
Sembla ser un problema de codi. Seguirem mirant i intentarem solucionarlo i donar el codi correcte.

**Comment by teyteymey** [comment]
El codi ha passat tots els test. Provaré en local i informaré per pujar els canvis a production.

**Comment by teyteymey** [comment]
he solucionat uns bugs que sortien i refactoritzat el codi.
llest pel deployment
