### ISSUE TITLE
Existeix un profile 'ASW12' que pensem que s'hauria d'esborrar

### ISSUE THREAD

**Issue by carlesf** [Learning-Dashboard/Bug-Reporting#42]
Hem vist un error de configuració tonto que no crec que sigui urgent però estaria bé arreglar en un moment donat. Al clickar sobre el botó que hi ha a la dreta de "Project" per seleccionar el projecte, hi ha un desplegable 'Profile', i apareix sempre com a opció el profile 'asw12a' (encara que l'usuari sigui un grup de PES). Seleccionant el profie 'asw12' no fa res, però s'hauria de treure...

**Comment by teyteymey** [comment]
Se me olvidó borrarlo al hacer pruebas. Hecho!
