### ISSUE TITLE
Equips ASW: pulir detalls al Learning Dashboard

### ISSUE THREAD

**Issue by carlesf** [Learning-Dashboard/Bug-Reporting#43]
**Course: ASW**

**Project group id: All**

**Describe the bug**
- Posar els links a GitHub i Taiga al costat de les mètriques
- El botó d'informació "i" en molts casos no mostra res
- Definir els Sprints d'ASW per a tots els equips:
  * Sprint 1: de 07/10/2022 a 11/11/2022
  * Sprint 2: de 12/11/2022 a 02/12/2022
  * Sprint 3: de 03/12/2022 a 23/12/2022

**Comment by teyteymey** [comment]
fet!
