### ISSUE TITLE
Equips ASW: Problemes amb les dades

### ISSUE THREAD

**Issue by carlesf** [Learning-Dashboard/Bug-Reporting#44]
**asw12b**
El número de commits (i línies modificades) del periòde pel qual es mostren dades (5.nov a 14.nov) es manté constant. Anant al GitHub d'aquest equip es veu que sí que hi ha hagut nous commits.

**asw13b**
Una estudiant no ha posat correctament el seu username de GitHub (hauria de ser "huiwen8" i no "huiwen85"), així que al LD li posa commits = 0.

**asw13c**
No agafa correctament les mètriques del taiga, surten totes a 0. Mirant el Taiga sí que tenen tasques asignades i completades

**Comment by lauracazorla** [comment]
Ja està arreglat, però esperarem fins demà per assegurar-nos que s'actualitza bé automàticament.
