### ISSUE TITLE
Metrics of a detailed factor not showing up

### ISSUE THREAD

**Issue by lauracazorla** [Learning-Dashboard/Bug-Reporting#46]
**Course: ASW and PES**

**Project group id: all**

**Describe the bug**
When accessing the metrics that compose a factor, through the sceen "Detailed Factors", no metrics appear. 

**To Reproduce**
1. Select a project.
2. Go to the "Factors" screen.
3. Press on the name of any factor. You will be redirected to the "Detailed Factors" screen.
4. Press on the name of the detailed factor.

**Expected behavior**
Metrics should show up in the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/99802772/203351315-160ff83e-8222-4600-8fe1-deb058a3f2da.png)

**Technical context (if it is relevant):**
Not relevant.

**Additional context**
This happens because an API call has a typo. More specifically, the call is "/api/qualityFactors/metric/currentcurrent", where the word current is duplicated.

**Comment by teyteymey** [comment]
done
