### ISSUE TITLE
Literal en castellà

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#49]
**Course: PES**

**Project group id: professor-pes**

**Describe the bug**
El valor del literal informant que una mètrica val 0 és "Nada"

**To Reproduce**
1. Go to Metrics
2. Click on any metric who has a value 0.0
3. See reported issue

**Expected behavior**
El literal hauria d'estar en anglès, com la resta

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10616582/226622764-dcbe1889-ed77-4753-abd5-39b48d516edc.png)

**Technical context (if it is relevant):**

**Additional context**

**Comment by lauracazorla** [comment]
He aplicat un "temporal fix", però la solució definitiva està proposada a la Issue #55.
