### ISSUE TITLE
US template millorat

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#52]
**Course: PES**

**Project group id: professor-pes**

**Describe the improvement**
La mètrica sobre plantilla de les US només distingeix una forma correcte per a cada idioma. Si no se segueix el patró exacte, dóna error

**Where Affects**
A la computació de la mètrica sobre Information Completeness de la US

**Expected behavior**
Veig dues opcions: (1) enriquir el procés aplicant NLP bàsic per reconéixer formes similars; (2) definir la plantilla en un camp de Taiga

**Screenshots**

**Technical context (if it is relevant):**

**Additional context**

**Comment by carlesf** [comment]
Laura did it.
