### ISSUE TITLE
Multi-language and case-insensitive dashboard-related keywords

### ISSUE THREAD

**Issue by XavierFranchG** [Learning-Dashboard/Bug-Reporting#6]
**Course: PES**

**Project group id: PES-teacher**

**Describe the improvement**
Support all dashboard-related keywords in 3 languages (Catalan, Spanish, English) and case-insensitive. For instance: Tasca, Tarea, Task, TASK, TAsk, ...

**Where Affects**
Data collectors

**Expected behavior**
All input works for whatever language the developer uses

**Screenshots**
N/A

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by jdconejos** [comment]
The improvement has been added as described
