### ISSUE TITLE
Historical views are difficult to grasp

### ISSUE THREAD

**Issue by XavierFranch** [Learning-Dashboard/Bug-Reporting#9]
**Course: PES**

**Project group id: PES-TEACHER**

**Describe the improvement**
The information in historical views appears as a bunch of unstructured graphics (please see screenshot below). It would be great to allow grouping, by several factors

**Where Affects**
Metrics/HistoricChart

**Expected behavior**
I expect to be able to group-by several criteria:
- present metrics at the team level: so that I can have an overall view of the performance of the team, before I dig into the details of the individual members (I'm aware that this probably entails a subordinated issue, like defining metrics not only at member level, but also at team level)
- to be able to visualize all the detailed information of ONE member (i.e., all the metrics' values of one individual, together, probably grouped by factor, and factors grouped by indicators)
- to be able to visualize the detailed information of ONE metric (i.e., all the metric's values of all individual)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10616582/165261339-b65eae38-afd5-40a7-b2f0-45eaea0a14fd.png)

**Technical context (if it is relevant):**
N/A

**Additional context**
N/A

**Comment by carlesf** [comment]
We will implement a grouping. See other related issues.
